-- ADOMS SAPA PostgreSQL compatibility schema draft.
-- Static draft only: do not run until loading and constraint decisions are approved.
-- User-data columns are nullable TEXT to preserve CSV strings, including the empty string.
-- audit_log.log_id is the sole generated non-TEXT column, backed by executable legacy DDL.

CREATE SCHEMA IF NOT EXISTS adoms2;
SET search_path TO adoms2, public;

CREATE TABLE adoms2."action" (
  "action_id" text,
  "insp_id" text,
  "action_type" text,
  "due_date" text,
  "done_at" text,
  "result" text,
  "note" text,
  "task_id" text,
  "action_basis" text,
  "requested_by" text,
  "requested_at" text,
  "batch_id" text,
  "resubmit_note" text,
  "resubmitted_by" text,
  "started_at" text,
  "prev_action_type" text,
  "approval_status" text,
  "created_by" text,
  "submitted_at" text,
  "submitted_by" text,
  "approved_at" text,
  "approved_by" text,
  "rejected_at" text,
  "reject_reason" text,
  "created_at" text,
  "updated_at" text,
  "rejudged_insp_id" text
);

CREATE TABLE adoms2."annual_schedule" (
  "sched_id" text,
  "kind" text,
  "title" text,
  "month_from" text,
  "day_from" text,
  "month_to" text,
  "day_to" text,
  "basis" text,
  "source" text,
  "href" text,
  "note" text
);

CREATE TABLE adoms2."asset" (
  "asset_id" text,
  "asset_name" text,
  "asset_gbn" text,
  "asset_kind" text,
  "asset_class" text,
  "safety_grade" text,
  "completed_ymd" text,
  "addr" text,
  "dept_id" text,
  "source" text,
  "sapa_l2_result" text,
  "sapa_basis" text,
  "need_data" text,
  "verified" text,
  "subject_tier" text,
  "subject_name" text,
  "subject_source" text,
  "subject_note" text,
  "mgmt_class" text,
  "mgmt_laws" text,
  "res_storage_k" text,
  "res_dam_height" text,
  "res_emergency_plan" text,
  "consign" text,
  "consign_note" text,
  "deleted" text
);

CREATE TABLE adoms2."asset_target_map" (
  "asset_id" text,
  "target_code" text,
  "basis" text,
  "confidence" text
);

CREATE TABLE adoms2."audit_log" (
  "log_id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "table_name" text,
  "row_key" text,
  "action" text,
  "changed_by" text,
  "changed_at" text,
  "before_json" text,
  "after_json" text,
  "note" text
);

CREATE TABLE adoms2."budget_exec" (
  "exec_id" text,
  "budget_id" text,
  "exec_date" text,
  "exec_desc" text,
  "amount" text,
  "evidence_name" text,
  "evidence_url" text,
  "created_by" text,
  "created_at" text
);

CREATE TABLE adoms2."ceo_activity" (
  "activity_id" text,
  "activity_date" text,
  "activity_type" text,
  "title" text,
  "place" text,
  "target_code" text,
  "asset_id" text,
  "dept_id" text,
  "participants" text,
  "finding" text,
  "instruction" text,
  "follow_up_task_id" text,
  "created_by" text,
  "note" text,
  "evidence_file" text,
  "created_at" text
);

CREATE TABLE adoms2."civil_manual" (
  "manual_id" text,
  "clause_ref" text,
  "record_kind" text,
  "title" text,
  "covers" text,
  "missing" text,
  "basis" text,
  "asset_id" text,
  "facility_name" text,
  "enacted_at" text,
  "revised_at" text,
  "done_at" text,
  "last_check_at" text,
  "reported_at" text,
  "participants" text,
  "owner_staff_id" text,
  "note" text,
  "evidence_name" text,
  "evidence_url" text
);

CREATE TABLE adoms2."civil_record" (
  "action_done_at" text,
  "record_id" text,
  "clause_ref" text,
  "record_kind" text,
  "title" text,
  "target_ref" text,
  "asset_id" text,
  "facility_name" text,
  "plan_year" text,
  "done_at" text,
  "half" text,
  "checker_staff_id" text,
  "r1" text,
  "r2" text,
  "r3" text,
  "r4" text,
  "covers" text,
  "content" text,
  "action_kind" text,
  "action_needed" text,
  "action_due" text,
  "evidence_name" text,
  "evidence_url" text,
  "ceo_reported" text,
  "reported_at" text,
  "report_method" text,
  "report_proxy" text,
  "created_by" text,
  "note" text
);

CREATE TABLE adoms2."civil_safety_plan" (
  "plan_id" text,
  "plan_year" text,
  "facility_kind" text,
  "asset_id" text,
  "facility_name" text,
  "asset_gbn" text,
  "asset_kind" text,
  "asset_class" text,
  "dept_id" text,
  "plan_status" text,
  "plan_basis" text,
  "ceo_confirmed" text,
  "confirmed_at" text,
  "mok_ga" text,
  "mok_na" text,
  "mok_da" text,
  "items_planned" text,
  "items_done" text,
  "established_at" text,
  "owner_staff_id" text,
  "note" text,
  "confirm_proxy" text,
  "confirmed_by" text
);

CREATE TABLE adoms2."compliance_task" (
  "task_id" text,
  "assign_id" text,
  "period_label" text,
  "due_date" text,
  "status" text,
  "done_at" text,
  "done_by" text,
  "remark" text,
  "approval_status" text,
  "submitted_at" text,
  "submitted_by" text,
  "check_result" text,
  "reject_reason" text,
  "rejected_at" text,
  "approved_at" text,
  "approved_by" text,
  "created_at" text,
  "updated_at" text,
  "period_year" text,
  "half_year" text,
  "plan_date" text,
  "evidence_cnt" text,
  "created_by" text,
  "entered_in_demo" text,
  "resubmit_round" text,
  "resubmit_note" text,
  "head_ok_at" text,
  "head_ok_by" text
);

CREATE TABLE adoms2."contract" (
  "contract_id" text,
  "contract_name" text,
  "counterpart" text,
  "asset_id" text,
  "dept_id" text,
  "contract_type" text,
  "start_date" text,
  "end_date" text,
  "amount" text,
  "safety_clause" text,
  "evaluation_done" text,
  "contract_method" text,
  "trade" text,
  "safety_cost" text,
  "worker_cnt" text,
  "subcontract" text,
  "eval_score" text,
  "eval_date" text,
  "manager_staff_id" text,
  "manager_phone" text,
  "work_start_date" text,
  "main_task" text,
  "work_place" text,
  "vendor_rep_role" text,
  "vendor_safety_role" text,
  "vendor_contact_on_file" text,
  "vendor_doc_status" text,
  "regular_workers" text,
  "attachments" text,
  "entrust_type" text,
  "apply_frame" text,
  "civil_scope" text,
  "civil_basis" text,
  "ctl_own" text,
  "ctl_lease" text,
  "ctl_repair" text,
  "ctl_command" text,
  "ctl_vendor_site" text,
  "control_result" text,
  "control_basis" text,
  "control_confirmed_at" text,
  "control_confirmed_by" text,
  "work_risk" text,
  "eval_pass_mark" text,
  "eval_detail" text,
  "proc_stage" text,
  "order_at" text,
  "contract_at" text,
  "completed_at" text,
  "settled_at" text,
  "cost_planned" text,
  "cost_settled" text,
  "note" text,
  "created_at" text,
  "updated_at" text
);

CREATE TABLE adoms2."contract_compliance" (
  "cc_id" text,
  "contract_id" text,
  "item_no" text,
  "item_code" text,
  "status" text,
  "evidence_name" text,
  "checked_at" text,
  "finding" text,
  "note" text,
  "checked_by" text,
  "evidence_url" text
);

CREATE TABLE adoms2."contract_duty" (
  "cduty_id" text,
  "contract_id" text,
  "duty_key" text,
  "status" text,
  "done_at" text,
  "evidence_id" text,
  "note" text
);

CREATE TABLE adoms2."contract_eval_item" (
  "item_no" text,
  "item_code" text,
  "group_code" text,
  "group_name" text,
  "item_name" text,
  "pt_good" text,
  "pt_mid" text,
  "pt_low" text,
  "mid_hint" text,
  "low_hint" text,
  "default_weight" text,
  "source" text,
  "basis" text,
  "basis_unit_id" text
);

CREATE TABLE adoms2."contract_eval_score" (
  "score_id" text,
  "contract_id" text,
  "eval_date" text,
  "work_risk" text,
  "pass_mark" text,
  "total" text,
  "result" text,
  "weights" text,
  "evaluated_by" text,
  "note" text,
  "p1" text,
  "p2" text,
  "p3" text,
  "p4" text,
  "p5" text,
  "p6" text,
  "p7" text,
  "p8" text,
  "p9" text,
  "p10" text
);

CREATE TABLE adoms2."contract_eval_setting" (
  "setting_id" text,
  "pass_default" text,
  "pass_general" text,
  "pass_risk" text,
  "pass_fire" text,
  "weights" text,
  "set_at" text,
  "set_by" text
);

CREATE TABLE adoms2."contract_hazard" (
  "hazard_id" text,
  "contract_id" text,
  "hazard_place" text,
  "hazard_factor" text,
  "risk_level" text,
  "measure" text
);

CREATE TABLE adoms2."contract_hazard_map" (
  "hazard_id" text,
  "contract_id" text,
  "hazard_code" text,
  "map_basis" text,
  "source_text" text
);

CREATE TABLE adoms2."contract_mgmt_item" (
  "item_no" text,
  "item_code" text,
  "item_name" text,
  "basis" text,
  "basis_unit_id" text,
  "basis_text" text,
  "applies_to" text,
  "evidence_hint" text
);

CREATE TABLE adoms2."drill_eval" (
  "eval_id" text,
  "drill_id" text,
  "evaluator" text,
  "evaluated_at" text,
  "p1" text,
  "p2" text,
  "p3" text,
  "p4" text,
  "c1" text,
  "c2" text,
  "x1" text,
  "x2" text,
  "x3" text,
  "x4" text,
  "e1" text,
  "e2" text,
  "total" text,
  "comment" text,
  "note" text
);

CREATE TABLE adoms2."drill_plan" (
  "drill_id" text,
  "target_key" text,
  "target_name" text,
  "target_kind" text,
  "asset_class" text,
  "legal_scope" text,
  "dept_id" text,
  "year" text,
  "half" text,
  "drill_type" text,
  "method" text,
  "planned_at" text,
  "place" text,
  "scenario" text,
  "target_minutes" text,
  "prep_coop" text,
  "prep_items" text,
  "prep_budget" text,
  "prep_memo" text,
  "carry_over" text,
  "r_cmd_main" text,
  "r_cmd_sub" text,
  "r_evac_main" text,
  "r_evac_sub" text,
  "r_resp_main" text,
  "r_resp_sub" text,
  "r_aid_main" text,
  "r_aid_sub" text,
  "r_eval_main" text,
  "r_eval_sub" text,
  "status" text,
  "done_at" text,
  "actual_minutes" text,
  "participants" text,
  "absent" text,
  "photos" text,
  "good_points" text,
  "shortfalls" text,
  "improvements" text,
  "substitute" text,
  "substitute_basis" text,
  "ceo_checked" text,
  "ceo_checked_at" text,
  "ceo_check_mode" text,
  "note" text
);

CREATE TABLE adoms2."duty_assignment" (
  "assign_id" text,
  "duty_key" text,
  "asset_id" text,
  "scope" text,
  "target_code" text,
  "dept_id" text,
  "owner_staff_id" text,
  "deputy_staff_id" text,
  "applicability" text,
  "applicability_note" text,
  "cycle" text,
  "cycle_days" text,
  "decided_by" text,
  "decided_at" text,
  "badge" text,
  "created_at" text,
  "updated_at" text,
  "plan_input_type" text
);

CREATE TABLE adoms2."duty_class" (
  "duty_key" text,
  "yongin_mark" text,
  "area" text,
  "code36" text,
  "code36_name" text,
  "task_name" text,
  "target_code" text,
  "target_name" text,
  "impl_type" text,
  "impl_type_name" text,
  "law_group" text,
  "law_group_name" text,
  "law" text,
  "doc" text,
  "layer" text,
  "unit_label_ko" text,
  "article_title" text,
  "duty_name" text,
  "verdict" text,
  "duty_subject" text,
  "cycle_text" text,
  "assign_basis" text,
  "evidence_kind" text,
  "badge" text,
  "why" text,
  "source_text" text,
  "law_id" text,
  "doc_id" text,
  "unit_id" text,
  "schedule_id" text,
  "obl_id" text,
  "review_status" text,
  "rev_state" text,
  "rev_at" text,
  "rev_run" text,
  "rev_item" text,
  "rev_text" text,
  "rev_note" text,
  "retired" text,
  "sapa_clause" text,
  "sapa_clause_name" text
);

CREATE TABLE adoms2."eval_criteria" (
  "criteria_id" text,
  "target_role" text,
  "item_no" text,
  "item" text,
  "points" text,
  "law_basis" text,
  "active" text,
  "note" text
);

CREATE TABLE adoms2."evidence" (
  "evidence_id" text,
  "task_id" text,
  "evidence_kind" text,
  "file_name" text,
  "file_url" text,
  "form_id" text,
  "uploaded_by" text,
  "uploaded_at" text,
  "note" text,
  "file_size" text,
  "file_type" text,
  "mime_type" text,
  "approval_status" text,
  "created_by" text,
  "submitted_at" text,
  "submitted_by" text,
  "approved_at" text,
  "approved_by" text,
  "rejected_at" text,
  "reject_reason" text,
  "created_at" text,
  "updated_at" text,
  "entered_in_demo" text
);

CREATE TABLE adoms2."evidence_split" (
  "split_id" text,
  "pair_key" text,
  "act" text,
  "file_name" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."form_template" (
  "form_id" text,
  "title" text,
  "doc_id" text,
  "law_id" text,
  "schedule_kind" text,
  "schedule_no" text,
  "source" text,
  "file_html" text,
  "file_docx" text,
  "canon_release" text
);

CREATE TABLE adoms2."hazard_code" (
  "hazard_code" text,
  "hazard_name" text,
  "sort_no" text,
  "note" text
);

CREATE TABLE adoms2."hazard_report" (
  "hz_id" text,
  "received_at" text,
  "channel" text,
  "channel_detail" text,
  "reporter" text,
  "received_by" text,
  "asset_id" text,
  "asset_name" text,
  "asset_gbn" text,
  "asset_class" text,
  "dept_id" text,
  "location" text,
  "description" text,
  "code_group" text,
  "code" text,
  "accident_type" text,
  "possible_accident" text,
  "photo_wide" text,
  "photo_close" text,
  "protect_action" text,
  "protect_at" text,
  "protect_by" text,
  "severity" text,
  "judged_by" text,
  "judged_at" text,
  "judge_memo" text,
  "minor_action" text,
  "closed_at" text,
  "closed_by" text,
  "notified_reporter" text,
  "notified_at" text,
  "ceo_reported_at" text,
  "ceo_report_mode" text,
  "ceo_reported_by" text,
  "ceo_instruction" text,
  "insp_at" text,
  "insp_by" text,
  "insp_result" text,
  "order_types" text,
  "order_at" text,
  "order_memo" text,
  "fsam_applies" text,
  "basis_date" text,
  "fix_items" text,
  "fix_budget" text,
  "fix_started_at" text,
  "fix_done_at" text,
  "done_at" text,
  "note" text
);

CREATE TABLE adoms2."hazard_step" (
  "step_id" text,
  "hz_id" text,
  "step" text,
  "at" text,
  "by" text,
  "memo" text,
  "note" text
);

CREATE TABLE adoms2."incident" (
  "incident_id" text,
  "occurred_at" text,
  "disaster_type" text,
  "asset_id" text,
  "dept_id" text,
  "summary" text,
  "cause" text,
  "casualties" text,
  "recurrence_plan" text,
  "plan_due" text,
  "plan_done_at" text,
  "note" text,
  "event_class" text,
  "event_area" text,
  "serious" text,
  "accident_type" text,
  "place" text,
  "basis_clause" text,
  "reported_by" text,
  "owner_staff_id" text,
  "cause_due" text,
  "investigated_at" text,
  "investigated_by" text,
  "cause_evidence" text,
  "plan_set_due" text,
  "plan_set_at" text,
  "plan_set_by" text,
  "plan_evidence" text,
  "done_note" text,
  "done_evidence" text,
  "done_by" text,
  "effect_due" text,
  "effect_checked_at" text,
  "effect_checked_by" text,
  "effect_result" text,
  "effect_note" text,
  "effect_evidence" text,
  "related_order_id" text,
  "check_note" text,
  "cause_evidence_url" text,
  "plan_evidence_url" text,
  "done_evidence_url" text,
  "history" text,
  "reopen_count" text
);

CREATE TABLE adoms2."incident_nil_check" (
  "nil_id" text,
  "period" text,
  "dept_id" text,
  "confirmed_by" text,
  "confirmed_at" text,
  "memo" text,
  "note" text
);

CREATE TABLE adoms2."incident_report" (
  "report_id" text,
  "incident_id" text,
  "report_stage" text,
  "seq" text,
  "reported_at" text,
  "reporter_staff_id" text,
  "recipients" text,
  "agency_name" text,
  "channel" text,
  "overview" text,
  "damage" text,
  "rescue" text,
  "recovery" text,
  "support" text,
  "next_plan" text,
  "evidence_name" text,
  "evidence_url" text,
  "ceo_ack_at" text,
  "ceo_ack_by" text,
  "ceo_ack_proxy" text,
  "ceo_ack_recorded_by" text,
  "recorded_by" text,
  "recorded_at" text,
  "note" text
);

CREATE TABLE adoms2."incident_response" (
  "resp_id" text,
  "incident_id" text,
  "kind" text,
  "status" text,
  "done_at" text,
  "done_by" text,
  "target_org" text,
  "detail" text,
  "evidence_name" text,
  "evidence_url" text,
  "proxy" text,
  "recorded_by" text,
  "recorded_at" text,
  "note" text
);

CREATE TABLE adoms2."incident_response_setting" (
  "set_id" text,
  "first_report_limit_min" text,
  "set_at" text,
  "set_by" text,
  "memo" text,
  "note" text
);

CREATE TABLE adoms2."inspection" (
  "insp_id" text,
  "task_id" text,
  "inspector_staff_id" text,
  "insp_date" text,
  "result" text,
  "finding" text,
  "note" text,
  "action_need" text,
  "round_no" text,
  "batch_id" text,
  "approval_status" text,
  "created_by" text,
  "submitted_at" text,
  "submitted_by" text,
  "approved_at" text,
  "approved_by" text,
  "rejected_at" text,
  "reject_reason" text,
  "created_at" text,
  "updated_at" text
);

CREATE TABLE adoms2."inspection_batch" (
  "batch_id" text,
  "title" text,
  "period_year" text,
  "half_year" text,
  "scope_dept_id" text,
  "target_dept_ids" text,
  "code36_list" text,
  "status" text,
  "started_by" text,
  "started_at" text,
  "approved_by" text,
  "note" text,
  "open_reason" text,
  "open_kind" text,
  "requested_by" text,
  "requested_at" text,
  "n_total" text,
  "n_ok" text,
  "n_fix" text,
  "n_bad" text,
  "n_open" text,
  "n_unsubmitted" text,
  "return_reason" text,
  "approved_at" text,
  "approve_note" text,
  "returned_at" text,
  "rule_basis" text,
  "insp_method" text,
  "outsource_org" text,
  "report_received_at" text,
  "report_received_by" text,
  "report_recorded_by" text,
  "report_proxy" text
);

CREATE TABLE adoms2."law_change" (
  "change_id" text,
  "law" text,
  "doc" text,
  "changed_kind" text,
  "promulgated_at" text,
  "effective_at" text,
  "affected_duty_cnt" text,
  "notice_sent_at" text,
  "note" text,
  "run_id" text,
  "status" text,
  "new_mst" text,
  "changed_units" text,
  "new_units" text,
  "removed_units" text,
  "human_items" text
);

CREATE TABLE adoms2."law_sync_applied" (
  "run_id" text,
  "applied_at" text,
  "by" text,
  "law_change_n" text,
  "duty_marked_n" text,
  "notified_n" text
);

CREATE TABLE adoms2."law_sync_decision" (
  "item_id" text,
  "run_id" text,
  "action" text,
  "decision" text,
  "by" text,
  "at" text,
  "note" text,
  "duty_keys" text
);

CREATE TABLE adoms2."material_item" (
  "item_id" text,
  "item_name" text,
  "dept_id" text,
  "owner_staff_id" text,
  "acts" text,
  "byeolpyo5" text,
  "related_law" text,
  "verdict" text,
  "reason" text,
  "basis_ref" text,
  "judged_by" text,
  "judged_at" text,
  "ceo_confirmed_at" text,
  "ceo_confirmed_by" text,
  "ceo_proxy" text,
  "updated_at" text,
  "created_by" text,
  "note" text
);

CREATE TABLE adoms2."notification" (
  "notif_id" text,
  "task_id" text,
  "notif_type" text,
  "to_staff_id" text,
  "sent_at" text,
  "message" text,
  "read_at" text,
  "note" text,
  "from_staff_id" text,
  "action_id" text,
  "batch_id" text
);

CREATE TABLE adoms2."order_received" (
  "order_id" text,
  "received_at" text,
  "issuer" text,
  "law" text,
  "content" text,
  "due_date" text,
  "dept_id" text,
  "asset_id" text,
  "done_at" text,
  "result" text,
  "evidence_file" text,
  "issuer_kind" text,
  "law_article" text,
  "order_no" text,
  "place" text,
  "owner_staff_id" text,
  "assigned_at" text,
  "action_plan" text,
  "started_at" text,
  "done_note" text,
  "done_by" text,
  "reported_at" text,
  "report_evidence" text,
  "closed_at" text,
  "closed_note" text,
  "extended_due" text,
  "extend_reason" text,
  "related_incident_id" text,
  "check_note" text,
  "doc_nature" text,
  "note" text,
  "order_area" text,
  "basis_clause" text
);

CREATE TABLE adoms2."org_dept" (
  "dept_id" text,
  "dept_name" text,
  "dept_role" text,
  "parent_dept_id" text,
  "org_path" text,
  "unit_kind" text,
  "duties" text,
  "related_note" text,
  "web_checked" text
);

CREATE TABLE adoms2."org_profile" (
  "org_id" text,
  "org_name" text,
  "org_type" text,
  "ceo_title" text,
  "disaster_agency" text,
  "sapa_scope" text,
  "hq_addr" text,
  "hq_built" text,
  "hq_floors" text,
  "hq_gfa" text,
  "hq_site" text,
  "hq_annex" text,
  "area_km2" text,
  "population" text,
  "districts" text,
  "phone" text,
  "updated_at" text,
  "updated_by" text
);

CREATE TABLE adoms2."risk_assessment" (
  "risk_id" text,
  "title" text,
  "dept_id" text,
  "place" text,
  "method" text,
  "assessed_at" text,
  "assessor_staff_id" text,
  "worker_joined" text,
  "review_cycle" text,
  "next_due" text,
  "status" text,
  "note" text,
  "wp_id" text,
  "kind" text,
  "targets" text,
  "source" text,
  "created_at" text
);

CREATE TABLE adoms2."risk_assessment_item" (
  "risk_item_id" text,
  "risk_id" text,
  "hazard_factor" text,
  "hazard_kind" text,
  "risk_level" text,
  "measure" text,
  "measure_due" text,
  "measure_done_at" text,
  "owner_staff_id" text,
  "note" text,
  "freq" text,
  "sev" text,
  "score" text,
  "current_measure" text,
  "residual_level" text
);

CREATE TABLE adoms2."safety_budget" (
  "budget_id" text,
  "fiscal_year" text,
  "dept_id" text,
  "target_code" text,
  "budget_kind" text,
  "budget_item" text,
  "budget_use" text,
  "use_basis" text,
  "planned_amount" text,
  "executed_amount" text,
  "risk_item_id" text,
  "duty_key" text,
  "updated_at" text,
  "note" text,
  "area" text
);

CREATE TABLE adoms2."safety_manual" (
  "manual_id" text,
  "clause_no" text,
  "title" text,
  "covers" text,
  "missing" text,
  "enacted_at" text,
  "revised_at" text,
  "last_check_at" text,
  "owner_staff_id" text,
  "note" text
);

CREATE TABLE adoms2."safety_org_role" (
  "role_id" text,
  "role_item" text,
  "scope" text,
  "dept_id" text,
  "designated" text,
  "status" text,
  "method" text,
  "designated_at" text,
  "law_basis" text,
  "clause_no" text,
  "staff_id" text,
  "doc_name" text,
  "last_eval_at" text,
  "note" text,
  "evidence_url" text
);

CREATE TABLE adoms2."safety_policy" (
  "policy_id" text,
  "clause_no" text,
  "policy_kind" text,
  "title" text,
  "fiscal_year" text,
  "summary" text,
  "enacted_at" text,
  "revised_at" text,
  "posted" text,
  "posted_where" text,
  "approver_role" text,
  "owner_staff_id" text,
  "note" text
);

CREATE TABLE adoms2."staff" (
  "staff_id" text,
  "display_name" text,
  "dept_id" text,
  "duty_role" text,
  "position" text,
  "approval_level" text,
  "email" text,
  "phone" text,
  "note" text
);

CREATE TABLE adoms2."sys_code" (
  "code_id" text,
  "set_id" text,
  "value" text,
  "sort" text,
  "state" text,
  "note" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."sys_mail_log" (
  "mail_id" text,
  "msg_id" text,
  "at" text,
  "notif_type" text,
  "from_staff_id" text,
  "to_staff_id" text,
  "to_name" text,
  "to_dept" text,
  "to_email" text,
  "subject" text,
  "status" text,
  "error" text
);

CREATE TABLE adoms2."sys_menu" (
  "menu_rid" text,
  "data" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."system_record" (
  "record_id" text,
  "clause_no" text,
  "mok" text,
  "record_kind" text,
  "title" text,
  "target_role" text,
  "target_ref" text,
  "target_staff_id" text,
  "dept_id" text,
  "done_at" text,
  "half" text,
  "checker_staff_id" text,
  "content" text,
  "action_needed" text,
  "action_done_at" text,
  "covers" text,
  "score" text,
  "item_scores" text,
  "substitute" text,
  "budget_amount" text,
  "doc_name" text,
  "ceo_reported" text,
  "reported_at" text,
  "report_method" text,
  "created_by" text,
  "note" text,
  "evidence_url" text,
  "report_proxy" text
);

CREATE TABLE adoms2."training_check" (
  "check_id" text,
  "area" text,
  "period" text,
  "half" text,
  "checked_at" text,
  "checked_by" text,
  "method" text,
  "proxy" text,
  "summary" text,
  "note" text
);

CREATE TABLE adoms2."training_course" (
  "course_id" text,
  "course_name" text,
  "law" text,
  "basis" text,
  "target" text,
  "cycle" text,
  "cycle_months" text,
  "required_hours" text,
  "applies_depts" text,
  "hazardous_work" text,
  "note" text,
  "area" text
);

CREATE TABLE adoms2."training_record" (
  "training_id" text,
  "staff_id" text,
  "dept_id" text,
  "course_id" text,
  "course_name" text,
  "law" text,
  "hours" text,
  "period" text,
  "due_date" text,
  "trained_at" text,
  "status" text,
  "certificate_file" text,
  "duty_key" text,
  "note" text,
  "instructed_at" text,
  "instructed_by" text,
  "instruct_due" text,
  "instruct_basis" text,
  "evidence_url" text,
  "done_by" text
);

CREATE TABLE adoms2."usa_order" (
  "order_id" text,
  "sent_at" text,
  "from_staff_id" text,
  "from_name" text,
  "track" text,
  "to_dept_ids" text,
  "to_names" text,
  "to_owners" text,
  "rates" text,
  "message" text,
  "channels" text,
  "results" text
);

CREATE TABLE adoms2."usb1_basic" (
  "basic_id" text,
  "track" text,
  "target_id" text,
  "base_date" text,
  "addr" text,
  "ind_class" text,
  "ind_code" text,
  "headcount" text,
  "workers" text,
  "sups" text,
  "files" text,
  "spec" text,
  "extra" text,
  "state" text,
  "saved_at" text,
  "saved_by" text
);

CREATE TABLE adoms2."usb1_contract" (
  "contract_id" text,
  "contract_name" text,
  "counterpart" text,
  "asset_id" text,
  "dept_id" text,
  "contract_type" text,
  "start_date" text,
  "end_date" text,
  "amount" text,
  "safety_clause" text,
  "evaluation_done" text,
  "contract_method" text,
  "trade" text,
  "safety_cost" text,
  "worker_cnt" text,
  "subcontract" text,
  "eval_score" text,
  "eval_date" text,
  "manager_staff_id" text,
  "manager_phone" text,
  "work_start_date" text,
  "main_task" text,
  "work_place" text,
  "vendor_rep_role" text,
  "vendor_safety_role" text,
  "vendor_contact_on_file" text,
  "vendor_doc_status" text,
  "regular_workers" text,
  "attachments" text,
  "entrust_type" text,
  "apply_frame" text,
  "civil_scope" text,
  "civil_basis" text,
  "ctl_own" text,
  "ctl_lease" text,
  "ctl_repair" text,
  "ctl_command" text,
  "ctl_vendor_site" text,
  "control_result" text,
  "control_basis" text,
  "control_confirmed_at" text,
  "control_confirmed_by" text,
  "work_risk" text,
  "eval_pass_mark" text,
  "eval_detail" text,
  "proc_stage" text,
  "order_at" text,
  "contract_at" text,
  "completed_at" text,
  "settled_at" text,
  "cost_planned" text,
  "cost_settled" text,
  "note" text,
  "order_dept" text,
  "manager_name" text,
  "vendor_manager" text,
  "vendor_phone" text,
  "biz_no" text,
  "place_codes" text,
  "attach" text,
  "updated_at" text,
  "updated_by" text
);

CREATE TABLE adoms2."usb1_contract_duty" (
  "cd_id" text,
  "contract_id" text,
  "item_code" text,
  "status" text,
  "files" text,
  "basis" text,
  "updated_at" text,
  "updated_by" text
);

CREATE TABLE adoms2."usb1_hazard_place" (
  "place_code" text,
  "no" text,
  "place_name" text,
  "note" text,
  "basis" text,
  "unit_id" text
);

CREATE TABLE adoms2."usb1_transport" (
  "tr_id" text,
  "tr_name" text,
  "tr_kind" text,
  "dept_id" text,
  "addr" text,
  "basis" text,
  "basis_unit_id" text,
  "law_family" text,
  "note" text
);

CREATE TABLE adoms2."usb1_work_site" (
  "site_id" text,
  "wp_id" text,
  "site_name" text,
  "site_kind" text,
  "addr" text,
  "org_note" text,
  "confirm_state" text,
  "src_url" text,
  "sort" text
);

CREATE TABLE adoms2."usb1_workplace" (
  "wp_id" text,
  "wp_name" text,
  "wp_kind" text,
  "addr" text,
  "addr_note" text,
  "site_note" text,
  "field_work" text,
  "field_basis" text,
  "org_note" text,
  "subject" text,
  "confirm_state" text,
  "src_url" text,
  "ind_class" text,
  "ind_code" text,
  "sort" text,
  "note" text
);

CREATE TABLE adoms2."usb1_ws_mgmt" (
  "dept_id" text,
  "state" text,
  "updated_at" text,
  "updated_by" text
);

CREATE TABLE adoms2."usb2_assign" (
  "map_id" text,
  "disaster" text,
  "staff_id" text,
  "targets" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."usb2_basic" (
  "dept_id" text,
  "site_name" text,
  "addr" text,
  "ind_class" text,
  "ind_code" text,
  "rule" text,
  "chief" text,
  "safety_mgr" text,
  "health_mgr" text,
  "doctor" text,
  "committee" text,
  "supervisor" text,
  "deleted" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."usb2_law" (
  "law_rid" text,
  "disaster" text,
  "area" text,
  "target_code" text,
  "target_name" text,
  "doc" text,
  "law" text,
  "layer" text,
  "n" text,
  "y" text,
  "apply" text,
  "state" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."usb2_role" (
  "rid" text,
  "disaster" text,
  "staff_id" text,
  "level" text,
  "kind" text,
  "state" text,
  "at" text,
  "by" text
);

CREATE TABLE adoms2."usb2_timing" (
  "rec_id" text,
  "track" text,
  "target_id" text,
  "saved_at" text,
  "by" text,
  "vals" text,
  "laws" text,
  "hidden" text
);

CREATE TABLE adoms2."usc_record" (
  "rec_id" text,
  "dept_id" text,
  "year" text,
  "step" text,
  "section" text,
  "parent_id" text,
  "ord" text,
  "locked" text,
  "deleted" text,
  "status" text,
  "data" text,
  "files" text,
  "updated_at" text,
  "updated_by" text,
  "site_id" text,
  "block" text,
  "seq" text
);

CREATE TABLE adoms2."usd_record" (
  "rec_id" text,
  "scope" text,
  "dept_id" text,
  "year" text,
  "step" text,
  "block" text,
  "ord" text,
  "deleted" text,
  "status" text,
  "data" text,
  "files" text,
  "updated_at" text,
  "updated_by" text
);

CREATE TABLE adoms2."use_plan" (
  "plan_id" text,
  "site_id" text,
  "step" text,
  "block" text,
  "data" text
);

CREATE TABLE adoms2."use_record" (
  "rec_id" text,
  "site_id" text,
  "dept_id" text,
  "year" text,
  "step" text,
  "block" text,
  "seq" text,
  "deleted" text,
  "status" text,
  "data" text,
  "files" text,
  "updated_at" text,
  "updated_by" text
);

CREATE TABLE adoms2."use_site" (
  "site_id" text,
  "site_name" text,
  "dept_id" text,
  "targets" text,
  "note" text
);

CREATE TABLE adoms2."usf_ceo_activity" (
  "updated_by" text,
  "updated_at" text,
  "activity_id" text,
  "evidence_name" text,
  "evidence_url" text,
  "created_by" text,
  "created_at" text,
  "proxy" text,
  "deleted" text,
  "deleted_by" text,
  "deleted_at" text
);

CREATE TABLE adoms2."usf_ceo_log" (
  "log_id" text,
  "at" text,
  "activity" text,
  "detail" text,
  "by" text
);

CREATE TABLE adoms2."usf_file" (
  "file_id" text,
  "category" text,
  "title" text,
  "body" text,
  "written_by" text,
  "created_at" text,
  "evidence_name" text,
  "evidence_url" text,
  "gen_content" text
);

CREATE TABLE adoms2."usf_judge" (
  "judge_id" text,
  "round_id" text,
  "track" text,
  "item_key" text,
  "dept_id" text,
  "status" text,
  "comment" text,
  "proposed" text,
  "basis" text,
  "judged_by" text,
  "judged_at" text
);

CREATE TABLE adoms2."usf_letter" (
  "letter_id" text,
  "title" text,
  "recipients" text,
  "related_duty" text,
  "body" text,
  "sent_at" text,
  "status" text,
  "sender" text,
  "written_by" text,
  "created_at" text,
  "evidence_name" text,
  "evidence_url" text
);

CREATE TABLE adoms2."usf_letter_read" (
  "read_id" text,
  "letter_id" text,
  "dept_id" text,
  "staff_id" text,
  "read_at" text
);

CREATE TABLE adoms2."usf_notice" (
  "notice_id" text,
  "title" text,
  "body" text,
  "pinned" text,
  "written_by" text,
  "created_at" text,
  "evidence_name" text,
  "evidence_url" text
);

CREATE TABLE adoms2."usf_round" (
  "round_id" text,
  "track" text,
  "title" text,
  "dept_ids" text,
  "item_keys" text,
  "status" text,
  "created_by" text,
  "created_at" text,
  "approved_by" text,
  "approved_at" text,
  "approve_note" text,
  "insp_method" text,
  "outsource_org" text,
  "report_received_at" text
);

CREATE TABLE adoms2."usg_case" (
  "case_no" text,
  "title" text,
  "dept_name" text,
  "writer" text,
  "writer_id" text,
  "created_at" text,
  "views" text,
  "content" text,
  "files" text,
  "deleted" text,
  "updated_at" text,
  "updated_by" text,
  "deleted_at" text,
  "deleted_by" text
);

CREATE TABLE adoms2."usg_stat_occur" (
  "occ_id" text,
  "year" text,
  "seq" text,
  "org_name" text,
  "dept_name" text,
  "occurred_at" text,
  "report_at" text,
  "approve_at" text,
  "comp" text,
  "disaster_kind" text,
  "lost_days" text,
  "work_type" text,
  "birth_year" text,
  "sex" text,
  "acc_type" text,
  "injury" text,
  "process" text,
  "job" text,
  "place" text,
  "cause" text,
  "note" text,
  "uploaded_by" text,
  "uploaded_file" text
);

CREATE TABLE adoms2."usg_ws_industry" (
  "dept_id" text,
  "workplace" text,
  "industry" text
);

CREATE TABLE adoms2."worker_voice" (
  "voice_id" text,
  "received_at" text,
  "channel" text,
  "dept_id" text,
  "content" text,
  "review_result" text,
  "action_taken" text,
  "closed_at" text,
  "stage" text,
  "needs_improvement" text,
  "reviewed_at" text,
  "reviewer_staff_id" text,
  "plan" text,
  "plan_due" text,
  "plan_owner_staff_id" text,
  "done_at" text,
  "substitute" text,
  "ceo_reported" text,
  "reported_at" text,
  "report_method" text,
  "note" text,
  "report_proxy" text
);


