BEGIN;

CREATE TABLE IF NOT EXISTS adoms2.demo_qa_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_type TEXT NOT NULL,
  route TEXT,
  role TEXT,
  http_status INTEGER,
  duration_ms DOUBLE PRECISION,
  cache_state TEXT,
  success BOOLEAN NOT NULL DEFAULT true,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  detail JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS demo_qa_event_occurred_at_idx ON adoms2.demo_qa_event (occurred_at DESC);
CREATE INDEX IF NOT EXISTS demo_qa_event_type_time_idx ON adoms2.demo_qa_event (event_type, occurred_at DESC);

COMMIT;
